package de.dentareport.gui.navigation;

public enum ViewId {
    COPY_FILES,
    EVALUATION,
    FILLINGS,
    GENERAL_INFORMATION_FILLINGS,
    GENERAL_INFORMATION_TELESCOPIC_CROWNS,
    GENERAL_PATIENT_INFORMATION,
    IMPORT_DATA,
    START,
    TELESCOPIC_CROWNS,
}

